### ISSUE TITLE
Generalize the curses visualization

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-filters#13]
We need a general terminal-based dashboard, to visualize the information captured of one server. The idea is that more than one visualization may be seen at the same time (or in different tab inside the same application). 

To do this, we may think something like a "scriptable-visualization"  (something like a framework), and for each PreR we may write a script of how to visualize this with the framework. This script may be in the same module (.py file) of the PreR.

Initially it has to work only with the topn PreR.

**Comment by emilio-aburto** [comment]
No longer applicable, please close.
