### ISSUE TITLE
Embed multiple python interpreters

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-filters#14]
Write the main loop of the filters program in C, start multiple threads, and embed one python subinterpreter for each configured PreR. Then, for each received packet send it to each subinterpreter and let it run through different threads. This may help to scale up the monitor when it runs in computers that have multiple cores (think in embedded ARM systems that have a lot of cores).

**Comment by franchoco** [comment]
Any update on this @raticate ?

**Comment by franchoco** [comment]
@raticate told me that python subinterpreters share some state between them, so the GIL affects them too. So, we may need a change in the design.

Buuuut, before that, we need to test if there is a significant change by adding multiple threads to this part. The only way to do this in python (2.7+) is with [multiprocessing](https://docs.python.org/2/library/multiprocessing.html).

**Comment by franchoco** [comment]
After doing some experiments, we came to the conclusion that we should migrate the codebase to C. That is represented in a new repository: ratadns-fievel. I will close this issue.

**Comment by madestro** [comment]
.

**Comment by franchoco** [comment]
This repo is completely deprecated.
