### ISSUE TITLE
Pause, Rewind, Play commands for the Viz

### ISSUE THREAD

**Issue by raticate** [niclabs/ratadns-filters#25]
So the user can pause when he sees strange behavior, rewind a little bit if he wasn't quick enough (this means to save some previous states) and then go back to the present time.

**Comment by emilio-aburto** [comment]
I've created some priority labels to assign order of importance in assigned issues. Priority of this?

**Comment by franchoco** [comment]
The rewind limit may be 10 minutes.

**Comment by emilio-aburto** [comment]
No longer applicable, please close. 
Issue moved to [niclabs/ratadns-ncurses-viz #2](https://github.com/niclabs/ratadns-ncurses-viz/issues/2)
