### ISSUE TITLE
Crash handling

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-filters#28]
We have to handle the crashes and recover the system gently.

- [x] Create a bash daemon.
- [x] Handle the exceptions in python.
- [x] Create a systemd daemon.

**Comment by sking32** [comment]
First bash daemon in https://github.com/niclabs/ratadns-filters/commit/4d186ee828c06337a24629f22450bdddd87ba9f1

**Comment by sking32** [comment]
Add handling python exceptions in https://github.com/niclabs/ratadns-filters/commit/936e824cd37cd626ba7eefca0c606e55e1cc4325

**Comment by franchoco** [comment]
Systemd daemon first version created. We don't need this right now, maybe in the future. To use the rata we just need a howto... Closing...
