### ISSUE TITLE
Complete PreR's documentation

### ISSUE THREAD

**Issue by sking32** [niclabs/ratadns-filters#44]
- Complexity Note
- ReductionRatio Note

for :
- [ ] AnswersNameCounter
- [ ] AlonePackets
- [ ] AnswersPerSecond
- [ ] Identity
- [ ] NameCounter
- [ ] NullPreR
- [ ] OnlyAnswers
- [ ] OnlyQueries
- [ ] PacketSummary
- [ ] PacketHasUnderscore
- [ ] PacketsPerSecond
- [ ] PacketsQueriesAndAnswersPerSecond
- [ ] QueriesNameCounter
- [ ] QueriesPerSecond
- [ ] QueriesWithUnderscoredName
- [ ] TopN
- [ ] TopNPP
- [ ] TopNQ

**Comment by sking32** [comment]
This is going to be done in https://github.com/niclabs/ratadns-fievel

**Comment by franchoco** [comment]
That is correct. Closing.
