### ISSUE TITLE
Create installation script

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-filters#45]
We need this module to be installable. We need some install.py script that install this module into the system's path or so.

**Comment by sking32** [comment]
Installation via setup.py file in https://github.com/niclabs/ratadns-filters/commit/7a211f2cace33c58deb19b14e1ebab4867734597

Issue :
- Configuration file is located in absolute path considering default installation directory(/usr/local)

**Comment by franchoco** [comment]
It is no problem to have it in an absolute path, if it is configured at installation time. It is working like this?

**Comment by sking32** [comment]
- Configuration file is located inside .egg in https://github.com/niclabs/ratadns-filters/commit/ea19a3605a2e83f370f01b0c0384670c5ea540c3

**Comment by sking32** [comment]
Software is now (d7d595ce78629771dc4a490cee7d363801e64f6f) installed with "python setup.py install --prefix=$PREFIX" which will place:

* The library inside an egg file in $PREFIX/lib/python2.7/site-packages/
* "rata.cfg" in $PREFIX/etc/
* "filters" script in $PREFIX/bin/
