### ISSUE TITLE
client_subnet2 should make request to IANA urls, instead of static TXT files

### ISSUE THREAD

**Issue by jaimesanz** [niclabs/ratadns-filters#52]
prers/client_subnet2 should construct its dictionaries by making requests to the following URLS, instead of reading files:
approved_tlds -> request to https://data.iana.org/TLD/tlds-alpha-by-domain.txt
funny_classes -> request to http://www.iana.org/assignments/dns-parameters/

This should be done because this data changes daily, and static files become obsolete quickly

**Comment by franchoco** [comment]
This repo is completely deprecated.
